[package]
name = "bru-web"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
iroh = { version = "1", default-features = false, features = ["tls-ring"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
qrcode = { version = "0.14.1", default-features = false, features = ["svg"] }

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1
strip = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-bulk-memory", "--enable-nontrapping-float-to-int", "--enable-sign-ext", "--enable-mutable-globals", "--enable-multivalue", "--enable-reference-types", "--enable-simd"]
